### ISSUE TITLE
close icon in modals are blue

### ISSUE THREAD

**Issue by jrauh** [dashframework/dashing#16]
dashing-icons are causing the close icon to be blue.

**Comment by Nevren** [comment]
Update dashboard to use latest version (dash-modal was updated to fix this issue)

**Comment by jrauh** [comment]
There's a deeper issue here with the `.button--transparent` class 
<img width="279" alt="screen shot 2018-02-01 at 8 16 31 am" src="https://user-images.githubusercontent.com/7129122/35683012-3e7eacfa-0728-11e8-9965-2edda5d55eaf.png">

**Comment by jrauh** [comment]
There is a fix in the `issue_16` branch. https://github.com/dashframework/dashing/pull/29
